config/routes.rb
Rails.application.routes.draw do
  get '/' => 'home#index'
  
  resources :users do

    resources :photos
  end

  resources :tags, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  
  get '/log-in' => "sessions#new"
  post '/log-in' => "sessions#create"
  get '/log-out' => "sessions#destroy", as: :log_out
  get '/user/:id/show-users' => "users#index", as: :show_users
  post '/user/:id/follow/:followee' => "follow#create", as: :follow
  delete '/user/:id/follow/:followee' => "follow#destroy", as: :unfollow
end

app/models/user.rb
class User<ActiveRecord::Base
  has_many :photos
  has_many :tags
  has_many :follows
  attr_accessor :password
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_confirmation_of :password
  before_save :encrypt_password
  validates :email, uniqueness: true

  validates :email, :presence => true
  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def is_email?
    self.email.include?('@') && self.email.include?('.')
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    @user.valid?
    if !@user.is_email?
      flash[:alert] = "Input a properly formatted email."
      redirect_to :back
    elsif @user.errors.messages[:email] != nil
      flash[:notice]= "That email " + @user.errors.messages[:email].first
      redirect_to :back
    elsif @user.save
      flash[:notice]= "Signup successful. Welcome to the site!"
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      redirect_to :back
    end
  end

  def new
  end

  def show
    # all registered users
    @users = User.all
    # logged in user
    @user = User.find(params[:id])
    # Follow records that logged in user is the follower
    follow = Follow.where(follower: params[:id])
    
    # a set of user_ids that the logged in user follows
    followees = Set[]
    follow.each do |f|
      followees.add(f.followee)
    end

    # get all the users that the logged in user follows
    followedUsers = User.find(followees.to_a.flatten)

    # this instance variable has all the photos tha must be displayed for a logged in user
    @allPhotos = []

    # photos that the logged in user has uploaded
    @user.photos.each do |uphd|
      @allPhotos.append(uphd)
    end

    # photos that the followees of the logged in user has updloaded
    followedUsers.each do |followedUser|
      followedUser.photos.each do |phd|
        @allPhotos.append(phd)
      end
    end
  
    # all photos sorted by created_at field by ascending order
    @allPhotos = @allPhotos.sort { |a,b| a.created_at <=> b.created_at }

    # we reverse it to get the descending orger
    @allPhotos = @allPhotos.reverse

    # have comment ans tag ready to bephotosContainer used
    @comment = Comment.new
    @tag = Tag.new

    # hash map with userId as key and array of photos as value sorted by time 
    @otherPhotosByUser = Hash.new
    # array with all the logged in user photos
    @loggedInUserPhotos = Array.new

    @allPhotos.each do |ph|
      if @user.id == ph.user_id
        @loggedInUserPhotos.push(ph)
      elsif @otherPhotosByUser.has_key?(ph.user_id)
        @otherPhotosByUser[ph.user_id].push(ph)
      else
        listOfPhotos = Array.new
        listOfPhotos.push(ph)
        @otherPhotosByUser[ph.user_id] = listOfPhotos
      end
    end

  end

  def index
    #find all the users
    @users = User.all

    #find the logged in user
    @user = User.find(params[:id])

    # get the Follow records in which the logged in user is the follower
    follow = Follow.where(follower: params[:id])

    # Aaset of user_ids that the logged in user follows
    followees = Set[]
    follow.each do |f|
      followees.add(f.followee)
    end

    # instance variable used in order for the view to display the follow or the unfollow button
    @followedUsers = followees.to_a
    
    # set to users all the user except the logged in one, no reason to follow myself
    @users = @users - [@user]

  end

  private
  def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :avatar)
  end


end

app/views/users/index.html.haml
.followPageTitle
    Registered Users

.userList
    - @users.each  do |u|
        .userListItem
            - if u.avatar_file_name
                = image_tag u.avatar.url(:thumb), class: "userImage small"
            .userName
                = u.email

            - if @followedUsers.include? u.id.to_s
                .followBtn  
                    = button_to "Unfollow", unfollow_path(@user.id, u.id), method: :delete, class: ['btn', 'btn-danger']
            - else
                .followBtn
                    = button_to "Follow", follow_path(@user.id, u.id), method: :post, class: ['btn', 'btn-primary']
    .backBtn
        = link_to 'Back to home', user_path(@user), class: ['btn', 'btn-info']

app/views/users/new.html.haml
.singUpContainer
  %h1 Sign Up
  = form_for User.new, class: "form-inline" do |f|
    = f.label :email
    = f.text_field :email
    = f.label :password
    = f.password_field :password
    = f.label :password_confirmation
    = f.password_field :password_confirmation
    %br/
    = f.label :avatar, 'Upload Avatar'
    = f.file_field :avatar
    .submitSingUpBtn
      = f.submit "Sign Up"

app/views/users/show.html.haml
.top_row
  .user_att
    - if @user.avatar_file_name
      = image_tag @user.avatar.url(:thumb), class: "userImage"
    %span= @user.email
  .buttonsGroup
    .follow_btn
      = link_to 'Follow Users', show_users_path(@user), class: ['btn', 'btn-primary']
    .logout_btn
      = link_to 'Logout', log_out_path, class: ['btn', 'btn-danger']
    .add_photo_btn
      = link_to 'Add Photo', new_user_photo_path(@user), class: ['btn', 'btn-success']


.photosContainer
  - if !@loggedInUserPhotos.empty?
    .well.col-sm-4.photoContainer
      .photoTitle
        - @users.each do |user|
          .uploadedBy
            - if user.id == @loggedInUserPhotos[0].user_id
              - if user.avatar_file_name
                = image_tag user.avatar.url(:thumb),class: "userImage small"
              %span{:class => "uploadedByField"}= user.email

      .wrapper
        %span{:class => "titleText", :id => "imageTitle"}= @loggedInUserPhotos[0].title
        .imageContainer
          = image_tag @loggedInUserPhotos[0].image.url(:medium), id: "slide"
        %div{:id => "hiddenImages"}
          - @loggedInUserPhotos.each do |photo|
            = image_tag photo.image.url(:medium), alt: photo.title
            

.photosContainer
  - @otherPhotosByUser.values.each do |userPhotos|
    - if !userPhotos.empty?
      .well.col-sm-4.photoContainer
        .photoTitle
          - @users.each do |user|
            .uploadedBy
              - if user.id == userPhotos[0].user_id
                - if user.avatar_file_name
                  = image_tag user.avatar.url(:thumb), class: "userImage small"
                %span{:class => "uploadedByField"}= user.email

        .wrapper
          %span{:class => "titleText"}= userPhotos[0].title
          .imageContainer
            = image_tag userPhotos[0].image.url(:medium), id: "slide"
          %div{:id => "hiddenImages"}
            - userPhotos.each do |photo|
              = image_tag photo.image.url(:medium), alt: photo.title
              